### PR TITLE
Devspaces client container

### PR DESCRIPTION
**Pull request by mangelajo**

### CODE REVIEW

**Comment by mangelajo** [comment]
This container can be consume from client devspaces with the purpose of
creating tests, interacting with jumpstarter, etc.

**Comment by NickCao** [comment]
What's the difference between this container and the client container we are currently shipping? (Apart from the labels)

**Comment by mangelajo** [comment]
> What's the difference between this container and the client container we are currently shipping? (Apart from the labels)

It's based on https://github.com/devfile/developer-images/blob/main/base/ubi9/Dockerfile which is ready-made to run under apache-che / devspaces.

**Comment by NickCao** [comment]
Really hope we have `include` directive in dockerfile :(

**Review by NickCao — APPROVED** [review]

**Comment by mangelajo** [comment]
> Really hope we have `include` directive in dockerfile :(

I completely agree!, I've had the same thought a thousand times.

**Pull request merged**
