### PR TITLE
Implement reading disk image from storage mux

### PR DESCRIPTION
**Pull request by NickCao**

### CODE REVIEW

**Comment by mangelajo** [comment]
Sorry for taking so long to attempt to merge it, It seems like now something is not working

**Comment by NickCao** [comment]
Those failing are the tasks marked as xfail, however the exceptions aren't catched by pytest in ci? (They do locally)

**Comment by NickCao** [comment]
The magic is: rerun.

**Comment by mangelajo** [comment]
Hey, thank you Nick! :-D

**Review by mangelajo — APPROVED** [review]

**Pull request merged**
