### PR TITLE
Add version command for Jumpstarter cli

### PR DESCRIPTION
**Pull request by oglok**
Simple version command for the CLI tool

### CODE REVIEW

**Comment by oglok** [comment]
@mangelajo I think we could add the version by injecting it using ldflags at compilation time, so for development we could add the git commit, for example, and once we release, we overwrite it with a semver. This is just a quick one, let me know what you wanna do.

**Comment by mangelajo** [comment]
> @mangelajo I think we could add the version by injecting it using ldflags at compilation time, so for development we could add the git commit, for example, and once we release, we overwrite it with a semver. This is just a quick one, let me know what you wanna do.

If we have a quick way of doing it, I guess it would be nice. I tend to forget updating that all the time when I have to ':D

**Comment by mangelajo** [comment]
I was looking at the new go 1.18 support that already embeds some git details that you can then use at runtime, but it doesn't include tags.


It think it is better to pass down git describe --tags as linker flags... (what you were proposing basically)..

```
$ git diff
diff --git a/Makefile b/Makefile
index 9015859..6db02c7 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,8 @@

+VERSION := $(shell git describe --tags)
+
 jumpstarter: main.go pkg/drivers/dutlink-board/*.go pkg/runner/* pkg/harness/*.go cmd/*.go pkg/tools/*.go
-       go build
+       go build --ldflags "-X main.VERSION=$(VERSION)"

 containers:
        podman build ./containers/ -f Containerfile -t quay.io/mangelajo/jumpstarter:latest
[majopela@fedora39 jumpstarter]$ make
go build --ldflags "-X main.VERSION=0.3.3-2-g74e1e3c"
```

**Comment by oglok** [comment]
Now it should be something like:

`Jumpstarter CLI Version:         0.3.3-2-g7fa9ffe`

**Comment by oglok** [comment]
Let me rebase

**Review by mangelajo — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
