### PR TITLE
Split jmp cli into client and exporter part

### PR DESCRIPTION
**Pull request by NickCao**

### CODE REVIEW

**Comment by NickCao** [comment]
TODO: replace the old cli doc with the generated ones.

**Comment by mangelajo** [comment]
We need to update this section: https://docs.jumpstarter.dev/installation/container-jmp.html#hardware-access-for-exporters

**Comment by NickCao** [comment]
> We need to update this section: https://docs.jumpstarter.dev/installation/container-jmp.html#hardware-access-for-exporters

We now need two alias.

**Comment by mangelajo** [comment]
> > We need to update this section: https://docs.jumpstarter.dev/installation/container-jmp.html#hardware-access-for-exporters
> 
> We now need two aliases.

oh, that too :)

Other than that I think it makes sense

**Review by mangelajo — APPROVED** [review]

**Pull request merged**
